site_name: My Blogs
site_url: https://wronganswer90.github.io
site_author: WrongAnswer90
strict: false

theme: 
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/brightness-7
        name: 切换至夜间模式
    - scheme: slate
      primary: black
      accent: white
      toggle: 
        icon: material/brightness-4
        name: 切换至白天模式
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.expand
    - search.share
  language: zh
  icon:
    repo: fontawesome/brands/github
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

edit_uri: edit/main/docs
repo_url: https://github.com/WrongAnswer90/WrongAnswer90.github.io
repo_name: WrongAnswer90.github.io

copyright: Copyright &copy; 2023 WrongAnswer90

hooks:
  - hooks/on_env.py

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/WrongAnswer90
    - icon: fontawesome/solid/paper-plane
      link: mailto:<wangyice1537@163.com>

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
      # slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - 'static/js/math-csr.js?math-csr'
  - 'assets/vendor/mathjax/es5/tex-mml-chtml.js?math-csr'

extra_css:
  - 'static/css/extra.css?v=14'

nav: 
  - Home: index.md
  - 缺省源: 缺省源/缺省源.md
  - 数学:
    - 多项式:
      - 多项式: Math/Poly/poly.md
      - 拉格朗日插值: Math/Poly/interpolation.md
      - 集合幂级数:
        - FWT: Math/Poly/FWT.md
        - 子集卷积: Math/Poly/subset.md
    - 数论:
      - 最大公约数(gcd):
        - 值域处理: Math/number theory/gcd/prework.md
        - binary gcd: Math/number theory/gcd/binary.md
        - exgcd: 
      - Miller-Rabin: Math/number theory/millerrabin.md
      - Pollard-Rho: Math/number theory/pollardrho.md
      - BSGS:
        - BSGS: 
        - exBSGS:
      - 扩展中国剩余定理(exCRT):
      - 原根: 
      - 筛法:
        - 杜教筛:
        - Min-25 筛:
      - dirichlet 前缀和:
      - mobius 反演:
    - 线性代数:
      - 行列式:
        - 行列式求值:
        - LGV 引理:
        - Best 定理:
        - Matrix-tree 定理:
      - 高斯消元:
      - 矩阵求逆:
    - 组合数学:
      - Lucas 定理:
      - exLucas 定理:
    - 排列置换相关:
      - Polya 定理:
      - prufer 序:
  - 字符串:
    - manacher:
    - 后缀数组(SA):
    - 后缀自动机(SAM):
    - 广义后缀自动机(GSAM):
    - AC 自动机(ACAM):
    - KMP:
    - exKMP:
    - 子序列自动机:
  - 图论:
    - 欧拉路:
    - dfs 序 LCA:
    - 流:
      - 最大流:
      - 费用流:
    - KM 算法:
    - 连通性:
      - 点双联通分量(圆方树):
      - 边双联通分量:
      - 强连通分量:
    - 最短路:
      - dijkstra:
      - SPFA:
    - 最小生成树:
    - 树哈希:
  - 数据结构:
    - 线段树:
      - 线段树:
      - 李超树:
      - 可持久化线段树:
    - 平衡树:
      - Splay:
      - FHQ treap:
      - 可持久化平衡树:
    - LCT:
    - 点分树: